### ISSUE TITLE
The Synthesis file is missing

### ISSUE THREAD

**Issue by DonghaiZHAO-ZJU** [qiangbo1222/Uni-RXN-official#1]
generation/generate_paths_reb.py
from Synthesis import init_LocalTransform, predict_product_batch
It seems like the Synthesis file is missing here.

**Comment by qiangbo1222** [comment]
Thanks for your interest in our work!
Synthesis file is in the LocalTransform folder, "sys.path.append('./LocalTransform')" will notice the python interpreter to find the module.

**Comment by DonghaiZHAO-ZJU** [comment]
Thanks for your answer.
I have other questions.
model/set_generation.py
line 110 batched_points = self.points[None, :].expand(batch_size, -1, -1)  # bs, n_max, set_c
I think the shape of batched_points isn't (bs, n_max, set_c) but (bs, point_num, set_c).

line 107 srted, indices = torch.topk(cosine, self.max_n, dim=1, largest=True, sorted=True)  # bs x n
Is the shape of cosine (bs, max_n)? So the function here is just to put them in order, and it does not play the role of picking out the top ones.

**Comment by qiangbo1222** [comment]
I think you might mix up the definition of max_n and n. max_n is the number of points that could be generated, n is the number of points we generated at the specific run. From line 107 to 110, we select the top max_n points based on cosine score and we select top n points later.

**Comment by DonghaiZHAO-ZJU** [comment]
Thanks for your answer. Happy Lantern Festival!
![Snipaste_2024-02-24_15-21-45](https://github.com/qiangbo1222/Uni-RXN-official/assets/138586178/6ff21941-724e-45df-8d83-971b8d522e2c)
Am I commenting correctly here?
If that's right, then isn't the function of the following line of code to take self.max_n out of self.max_n similarities? It only serve as a sort rather than a filter.
![Snipaste_2024-02-24_15-23-18](https://github.com/qiangbo1222/Uni-RXN-official/assets/138586178/5b94a247-4769-44f1-a02f-53a8a3d5c928)

**Comment by qiangbo1222** [comment]
Happy Lantern Festival to you as well!
n is set to 512 in our case, so the size of cosine should be (bs * 512). We keep top max_n=29 when running the torch.topk command. It should be a filter.

**Comment by DonghaiZHAO-ZJU** [comment]
I don't think so.
![Snipaste_2024-02-24_20-50-07](https://github.com/qiangbo1222/Uni-RXN-official/assets/138586178/a7945235-255f-4414-a84c-c07daa3264fe)
The following is the calculation for line 104 of the code:
1. shape of self.angles_params: (cfg.max_n, cfg.cosine_channels) _This is how the class TopNGenerator are defined when they are initialized_
2. shape of self.angles_params[None, ...]: (1,cfg.max_n, cfg.cosine_channels)
3. shape of angles: (batch_size, cfg.cosine_channels)
4. shape of angles[:, :, None]: (batch_size, cfg.cosine_channels,1)
5. shape of (self.angles_params[None, ...] @ angles[:, :, None]): (1,cfg.max_n, cfg.cosine_channels) @ (batch_size, cfg.cosine_channels,1) = (batch_size,cfg.max_n,1)
6. shape of (self.angles_params[None, ...] @ angles[:, :, None]).squeeze(dim=2): (batch_size,cfg.max_n)
7. shape of cosine: (batch_size,cfg.max_n)
Is there an error in my derivation? If so, please specify.

**Comment by qiangbo1222** [comment]
Sorry for the confusion by our old code. In our latest code, we have replaced the code in line 76 to:
`angles = torch.randn(cfg.point_num, cfg.cosine_channels).float()`
Thanks a lot for pointing it out. There won't be any noticeable performance difference when using only the max_n angles instead of n angles for generating new molecules. However, this would allow some users to generate much more diverse reactants if they want to use a bigger library for searching. Let me update the code and pretrained weights to the latest version next week.

**Comment by DonghaiZHAO-ZJU** [comment]
Okay, thank you for your patient response. I really appreciate your work.
