### ISSUE TITLE
Contrast learning task 2 lacks graph prediction of reagent

### ISSUE THREAD

**Issue by DonghaiZHAO-ZJU** [qiangbo1222/Uni-RXN-official#2]
![Snipaste_2024-02-24_23-01-25](https://github.com/qiangbo1222/Uni-RXN-official/assets/138586178/b5454935-8ea2-4097-9071-4f16858adb68)
It seems that graph_pred of reagents is missing here.

**Comment by qiangbo1222** [comment]
We delete reagent information in this loss objective after the submission of our paper, because it helps our reaction classification performance improve a little.

**Comment by DonghaiZHAO-ZJU** [comment]
Okay, I get it.

**Comment by DonghaiZHAO-ZJU** [comment]
![Snipaste_2024-03-03_11-57-06](https://github.com/qiangbo1222/Uni-RXN-official/assets/138586178/3f0b784f-e675-4cb3-b306-911e53d33b28)
How is the readout done here when obtaining the entity representation of the reaction? I don't think it's mentioned in the paper or the code.
And is there any code provided for the reaction classification task?

**Comment by qiangbo1222** [comment]
This readout is automatically done by the graphormer since the model does not have relative positional encoding as vanilla transformer. The information could be passed between atoms from different reactants.
