### ISSUE TITLE
Request for the dataset of Reaction Retrieval

### ISSUE THREAD

**Issue by zw-SIMM** [qiangbo1222/Uni-RXN-official#4]
You mentioned a Reaction Retrieval dataset in Figure 2a. 
`"We curated a dataset, as described in Methods, comprising positive examples of successful reactions and negative examples of noisy or suboptimal reactions. This dataset serves as a reliable benchmark for assessing our model’s capability to identify optimized reactions."`
Can you provide the splitted dataset?

@qiangbo1222

**Comment by qiangbo1222** [comment]
Thanks for your interest in our work!
 I will upload this dataset via a zenodo link in the readme of this repo. Please be patient. I am currently busy preparing to defend my thesis. Will get back to you soon.

**Comment by zw-SIMM** [comment]
> Thanks for your interest in our work! I will upload this dataset via a zenodo link in the readme of this repo. Please be patient. I am currently busy preparing to defend my thesis. Will get back to you soon.

Hope your defense goes smoothly!

**Comment by zw-SIMM** [comment]
How is it going?☺

**Comment by qiangbo1222** [comment]
Will update this week

**Comment by qiangbo1222** [comment]
'10.5281/zenodo.11426475' you can download the dataset here.

**Comment by qiangbo1222** [comment]
The dataset could be downloaded here: "https://zenodo.org/records/11426475"
