### ISSUE TITLE
how to represent the reaction entities

### ISSUE THREAD

**Issue by DonghaiZHAO-ZJU** [qiangbo1222/Uni-RXN-official#5]
When predicting reaction yields, how do you represent the reaction entities and how do you splice together the embedding of reactants, conditions, and products? When characterizing the reactants do you need to separate the reactants into main reactant and sub reactants to feed into the graph encoder separately? Do you need to consider the product?

**Comment by qiangbo1222** [comment]
The reactants are mixed and input into the graph encoder together. The reaction is represented by concatenating the embeddings of "reactants", "reagents" and "product".

**Comment by DonghaiZHAO-ZJU** [comment]
Thank you! Did you split the reactants to main reactant and sub reactants like the stage of pretrain for yield prediction.发自我的荣耀手机-------- 原始邮件 --------发件人： Bo Qiang ***@***.***>日期： 2024年6月3日周一 凌晨3:39收件人： qiangbo1222/Uni-RXN-official ***@***.***>抄送： abc1k ***@***.***>, Author ***@***.***>主    题： Re: [qiangbo1222/Uni-RXN-official] how to represent the reaction entities (Issue #5)
The reactants are mixed and input into the graph encoder together. The reaction is represented by concatenating the embeddings of "reactants", "reagents" and "product".
